language: php

php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
- travis_retry composer install --no-interaction

script:
- composer validate --strict
- find mollie tests -name *.php | xargs -n 1 -P4 php -l
- vendor/bin/phpunit -c tests/phpunit.xml
