version: "3.7"

services:
  mysql:
    volumes:
      - '~/mollie-mysql-db:/var/lib/mysql'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8082:8080'
    networks:
      - prestashop_mollie_net

