/// <reference types="Cypress" />
context('PS16 Partial Refunding, Full Refunding [Credit Card, iDeal, Klarna Pay Pater, Klarna Slice It]', () => {
  beforeEach(() => {
    cy.viewport(1920,1080)
    cy.mollie_test16_admin()
    cy.login_mollie16_test()
    cy.visit('https://demo.invertus.eu/clients/mollie16-test/admin1/index.php?controller=AdminOrders')
  })
it('Credit Card Refunding', () => {
      cy.get(':nth-child(9) > .filter').select('Payment accepted').wait(1000)
      cy.get(':nth-child(8) > .filter').type('Credit Card',{delay:0})
      cy.get('#submitFilterButtonorder').click()
      //Orders API order sum
      cy.contains('200').click().wait(3000)
      cy.get('.btn-group-action > .btn-group > .dropdown-toggle').click()
      cy.get('.btn-group-action > .btn-group > .dropdown-menu > :nth-child(1) > a').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Refund was made successfully!')
      cy.visit('https://demo.invertus.eu/clients/mollie16-test/admin1/index.php?controller=AdminOrders')
      cy.get(':nth-child(9) > .filter').select('Payment accepted').wait(1000)
      cy.get(':nth-child(8) > .filter').type('Credit Card',{delay:0})
      cy.get('#submitFilterButtonorder').click()
      //Payments API order sum
      cy.contains('100').click().wait(3000)
      cy.get('.form-inline > :nth-child(2) > .input-group > .form-control').type('1.51',{delay:0})
      cy.get(':nth-child(2) > .input-group > .input-group-btn > .btn').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Refund was made successfully!')
      cy.get('.form-inline > :nth-child(1) > .btn').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Refund was made successfully!').as('Successful PS16 Credit Card Refunding')
})
      it('iDeal Refunding', () => {
      cy.get(':nth-child(9) > .filter').select('Payment accepted').wait(1000)
      cy.get(':nth-child(8) > .filter').type('iDeal',{delay:0})
      cy.get('#submitFilterButtonorder').click()
      //Payments API order sum
      cy.contains('100').click().wait(3000)
      cy.get('.btn-group-action > .btn-group > .dropdown-toggle').click()
      cy.get('.btn-group-action > .btn-group > .dropdown-menu > :nth-child(1) > a').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Refund was made successfully!')
      cy.visit('https://demo.invertus.eu/clients/mollie16-test/admin1/index.php?controller=AdminOrders')
      cy.get(':nth-child(9) > .filter').select('Payment accepted').wait(1000)
      cy.get(':nth-child(8) > .filter').type('iDeal',{delay:0})
      cy.get('#submitFilterButtonorder').click()
      //Orders API order sum
      cy.contains('200').click().wait(3000)
      cy.get('.form-inline > :nth-child(2) > .input-group > .form-control').type('1.51',{delay:0})
      cy.get(':nth-child(2) > .input-group > .input-group-btn > .btn').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Refund was made successfully!')
      cy.get('.form-inline > :nth-child(1) > .btn').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Refund was made successfully!').as('Successful PS16 iDeal Refunding')
})
      it('Bancontact Refunding', () => {
      cy.get(':nth-child(9) > .filter').select('Payment accepted').wait(1000)
      cy.get(':nth-child(8) > .filter').type('Bancontact',{delay:0})
      cy.get('#submitFilterButtonorder').click()
      //Payments API order sum
      cy.contains('100').click().wait(3000)
      cy.get('.btn-group-action > .btn-group > .dropdown-toggle').click()
      cy.get('.btn-group-action > .btn-group > .dropdown-menu > :nth-child(1) > a').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Refund was made successfully!')
      cy.visit('https://demo.invertus.eu/clients/mollie16-test/admin1/index.php?controller=AdminOrders')
      cy.get(':nth-child(9) > .filter').select('Payment accepted').wait(1000)
      cy.get(':nth-child(8) > .filter').type('Bancontact',{delay:0})
      cy.get('#submitFilterButtonorder').click()
      //Orders API order sum
      cy.contains('200').click().wait(3000)
      cy.get('.form-inline > :nth-child(2) > .input-group > .form-control').type('1.51',{delay:0})
      cy.get(':nth-child(2) > .input-group > .input-group-btn > .btn').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Refund was made successfully!')
      cy.get('.form-inline > :nth-child(1) > .btn').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Refund was made successfully!').as('Successful PS16 Bancontact Refunding')
})
      it('Klarna Slice it Refunding', () => {
      cy.get(':nth-child(9) > .filter').select('Klarna payment authorized').wait(1000)
      cy.get(':nth-child(8) > .filter').type('Slice it',{delay:0})
      cy.get('#submitFilterButtonorder').click()
      //Orders API order sum
      cy.contains('200').click().wait(3000)
      cy.get('.btn-group > .btn-primary').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#input-carrier').type('FedEx')
      cy.get('#input-code').type('123456')
      cy.get('#input-url').type('https://www.invertus.eu')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Shipment was made successfully!')
      cy.get('.btn-group-action > .btn-group > .dropdown-toggle').click()
      cy.get('.btn-group-action > .btn-group > .dropdown-menu > :nth-child(1) > a').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Refund was made successfully!')
})
      it('Klarna Pay later Refunding', () => {
      cy.get(':nth-child(9) > .filter').select('Klarna payment authorized').wait(1000)
      cy.get(':nth-child(8) > .filter').type('Pay later',{delay:0})
      cy.get('#submitFilterButtonorder').click()
      //Orders API order sum
      cy.contains('200').click().wait(3000)
      cy.get('.btn-group > .btn-primary').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#input-carrier').type('FedEx')
      cy.get('#input-code').type('123456')
      cy.get('#input-url').type('https://www.invertus.eu')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Shipment was made successfully!')
      cy.get('.btn-group-action > .btn-group > .dropdown-toggle').click()
      cy.get('.btn-group-action > .btn-group > .dropdown-menu > :nth-child(1) > a').click()
      cy.get('.swal-modal').should('exist')
      cy.get(':nth-child(2) > .swal-button').click()
      cy.get('#mollie_order > :nth-child(1) > .alert').contains('Refund was made successfully!').as('Successful PS16 Klarna Payments Refunding')
})
})
