services:
  _defaults:
    public: true

  Mollie\Collector\ApplePayDirect\OrderTotalCollector:
    class: Mollie\Collector\ApplePayDirect\OrderTotalCollector
    arguments:
      - '@Mollie\Service\OrderPaymentFeeService'
