services:
  _defaults:
    public: true

  Mollie\Application\CommandHandler\RequestApplePayPaymentSessionHandler:
    class: 'Mollie\Application\CommandHandler\RequestApplePayPaymentSessionHandler'
    arguments:
      - '@mollie'
      - '@Mollie\Service\ApiService'
    tags:
      - { name: tactician.handler, command: Mollie\Application\Command\RequestApplePayPaymentSession }

  Mollie\Application\CommandHandler\UpdateApplePayShippingContactHandler:
    class: 'Mollie\Application\CommandHandler\UpdateApplePayShippingContactHandler'
    arguments:
      - '@Mollie\Builder\ApplePayDirect\ApplePayCarriersBuilder'
      - '@mollie.language'
      - '@Mollie\Service\OrderFeeService'
      - '@Mollie\Collector\ApplePayDirect\OrderTotalCollector'
    tags:
      - { name: tactician.handler, command: Mollie\Application\Command\UpdateApplePayShippingContact }

  Mollie\Application\CommandHandler\UpdateApplePayShippingMethodHandler:
    class: 'Mollie\Application\CommandHandler\UpdateApplePayShippingMethodHandler'
    arguments:
      - '@Mollie\Service\OrderFeeService'
    tags:
      - { name: tactician.handler, command: Mollie\Application\Command\RequestApplePayPaymentSession }

  Mollie\Application\CommandHandler\CreateApplePayOrderHandler:
    class: 'Mollie\Application\CommandHandler\CreateApplePayOrderHandler'
    arguments:
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\PaymentMethodService'
      - '@Mollie\Service\MollieOrderCreationService'
      - '@mollie.link'
      - '@mollie'
      - '@Mollie\Handler\RetryHandlerInterface'
    tags:
      - { name: tactician.handler, command: Mollie\Application\Command\RequestApplePayPaymentSession }
