FROM prestashop/prestashop:8.1.2-apache

RUN cd /usr/local/etc/php/conf.d/ && \
  echo 'memory_limit = 4096M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini

RUN echo 'max_execution_time = 120' >> /usr/local/etc/php/conf.d/docker-php-maxexectime.ini

